### ISSUE TITLE
Cpp14.g4 and InputMismatchException

### ISSUE THREAD

**Issue by BurtHarris** [mike-lischke/antlr4-c3#3]
Hi Mike, I'm just wrapping my head around what you've published here, but it seems really cool.

Oh snap, trying to fix the build for Windows, I'm getting 
```
test/CPP14Parser.ts(10179,78): error TS2304: Cannot find name 'InputMismatchException'.
```
Root cause seems to be CPP14.g4 : line 1097, a line mentioned in comments.   But it seems like the checked-in version of CPP14Parser.ts has the missing import.      I'm not clear why the checked-in version differs from what I've generated.

Adding the following to the .g4 seems to resolve:
```
@header {
	import { InputMismatchException } from 'antlr4ts/InputMismatchException';
}
```

Did you do something different?   If the above is good, assign this bug back to me, I've got a branch I've included it on.

**Comment by BurtHarris** [comment]
P.S. its been my practice to avoid checking in build-generated files like the TS file above.

**Comment by mike-lischke** [comment]
Well, the idea is to use the grammar as is, to show it really works with any grammar without the need to adjust it to make it run with antlr4-c3. But yes, that import is missing and I see no other way to get it in than adding that `@header` section to the grammar.

About the generated files in the repo:

1. I like to make it as easy as possible for a potential developer at the beginning. The way it is currently you can run the tests without further steps. Just clone and run `npm test`. OK, one could make the code generation part of the `test` script, but:
2. antlr4ts is still alpha and I had intermediate trouble running it. In order to avoid the same hassle for other devs the generated files are in the repo and the module can be used even if antlr4ts-cli is not working.

But I think, once antlr4ts has stabilized we can take out the generated files.
