### ISSUE TITLE
followSetsByATN is static and shouldn't be

### ISSUE THREAD

**Issue by nick-stephen** [mike-lischke/antlr4-c3#4]
The code has:
    private static followSetsByATN: Map<string, FollowSetsPerState> = new Map();

However in the tests, depending upon the test order, the contents of this are different,
in particular, if "Most simple setup" test is commented out and not invoked (this test initializes the above static map with data without any ignored tokens) , then "Typical setup" test fails,
because the ignored tokens affect what the follow sets are initialized with.

I'm not sure of the correct fix.

HTH!

**Comment by mike-lischke** [comment]
At line 166 begins `translateToRuleIndex` which doesn't use the ignored list (it collects rules not tokens, for which the ignored list used exclusively), so I don't know what you mean here. Also, `followSetsByATN` doesn't depend on the ignored tokens (it stores all following tokens starting from a given state). That means it can be filled in different order depending on what input is parsed, since that determines which states are visited. Still, that is a 1:1 relationship. The follow set depends only on a state, noting else.

But the tests should operate independently, unless explicitly said differently. If a following test fails because a previous test is not executed something is wrong, no doubt.

**Comment by nick-stephen** [comment]
ok - maybe my analysis is wrong, but my experimentation showed that if you comment out the body of the "Most simple setup" test then the "Typical setup" test fails, and the only thing shared between the two appears to be that static map. Thx!
