### ISSUE TITLE
[Question] Antlr-c3 with antlr4-ng runtime, issue with parser.getVocabulary()

### ISSUE THREAD

**Issue by Console-buche** [mike-lischke/antlr4-c3#84]
Hi,

I'm currently working on a typescript project involving Antlr4-c3. 
:warning: My issue/question might be premature as it is about version 3.2.1 which seems to introduce a breaking change. Apologies if it is premature and the feature is still under development.

**Description of the issue**
When installing version `3.1.1` everything runs perfectly fine.
When running version `3.2.1` though, I encountered an error on the parser class.

I figured that the Parser class in this latest tag version is imported from `antlr4-ng` instead of `antlr4` as is currently the case with `3.1.1`.

The `getVocabulary()` method doesn't seem to be implemented in the Parser class, which breaks code completion process.

![image](https://github.com/mike-lischke/antlr4-c3/assets/26569119/5eaaed52-6d88-4c51-b4c6-fc8d00891b74)

**Comment by mike-lischke** [comment]
Sorry for the trouble this switch caused for you. The problem is that antlr4ng is not fully ready like antlr4ts was. I'm actually hacking on it as we speak. It needs a custom-built antlr4 jar (just like antlr4ts) but has no interface yet to use it. What you have to do is to regenerate your parser files with [this custom jar](https://github.com/mike-lischke/antlr4ng/tree/master/antlr). In one of the next point releases I will provide an `antlr4ng-cli` node package, which can be used to generate the parser files easily (just like you did for your project using `antlr4ts-cli`.

**Comment by Console-buche** [comment]
Absolutely no worries, and thanks a lot for the quick and thorough response.
We'll be using `3.1.1` any way for now. It's great to see the current work you've been doing for supporting TS.
